# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 16:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('cuatrimestre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('AR', 'Araba'), ('GI', 'Gipuzkoa'), ('BI', 'Bizkaia')], max_length=10)),
                ('codigo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=140)),
                ('fechaCreacion', models.DateField(blank=True, default=datetime.date.today)),
                ('fechaUltimaModificacion', models.DateField(blank=True, default=datetime.date.today)),
                ('puntuacion', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatosTemporales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10)),
                ('especialidades', jsonfield.fields.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField()),
                ('eventos', jsonfield.fields.JSONField(blank=True)),
                ('datosTemporales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.DatosTemporales')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoIdioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreIdioma', models.CharField(choices=[('EU', 'Euskera'), ('EN', 'Ingles'), ('ES', 'Castellano')], max_length=10)),
                ('acronimoAsignatura', models.CharField(max_length=10)),
                ('nombreAsignatura', models.CharField(max_length=50)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.Grado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.Grado')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.Grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeGustaComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='MeGustaTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NivelCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=10)),
                ('inicioCuatrimestreUno', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Tiene que seguir el siguiente ejemplo: 'FEB 28, 2016' ", regex='((JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC) ([0-2][0-9]|3(0|1)), 20[1-9][0-9])')])),
                ('inicioCuatrimestreDos', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Tiene que seguir el siguiente ejemplo: 'FEB 28, 2016' ", regex='((JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC) ([0-2][0-9]|3(0|1)), 20[1-9][0-9])')])),
                ('finCuatrimestreUno', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Tiene que seguir el siguiente ejemplo: 'FEB 28, 2016' ", regex='((JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC) ([0-2][0-9]|3(0|1)), 20[1-9][0-9])')])),
                ('finCuatrimestreDos', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Tiene que seguir el siguiente ejemplo: 'FEB 28, 2016' ", regex='((JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC) ([0-2][0-9]|3(0|1)), 20[1-9][0-9])')])),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.Grado')),
            ],
        ),
        migrations.CreateModel(
            name='SubscripcionGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.Grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=140)),
                ('titulo', models.CharField(max_length=50)),
                ('Hora', models.TimeField(blank=True)),
                ('puntuacion', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField(default=0)),
                ('argumento', models.CharField(blank=True, max_length=140)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.Asignatura')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='megustatarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.Tarea'),
        ),
        migrations.AddField(
            model_name='datostemporales',
            name='grupoIdioma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datostemporales', to='asignaturas.GrupoIdioma'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='grupoIdioma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.GrupoIdioma'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.NivelCurso'),
        ),
    ]
